name: Aspect Workflows CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  aspect-workflows:
    name: Aspect Workflows
    uses: ./.github/workflows/aspect-workflows-template.yaml
